from enum import Enum

class RoleEnum(str, Enum):
    ADMINISTRATOR = "ADMINISTRATOR"
    AUTOMATION_MANAGER = "AUTOMATION_MANAGER"
    BILLING_MANAGER = "BILLING_MANAGER"
    BROADCAST_MANAGER = "BROADCAST_MANAGER"
    DEVELOPER = "DEVELOPER"
    DASHBOARD_VIEWER = "DASHBOARD_VIEWER"
    TEMPLATE_MANAGER = "TEMPLATE_MANAGER"
    OPERATOR = "OPERATOR"
    Contact_MANAGER = "Contact_MANAGER"



