from app.annotations.repositories.AttributeRepository import AttributeRepository
from app.annotations.repositories.ContactRepository import ContactRepository
from app.annotations.repositories.NoteRepository import NoteRepository
from app.annotations.services.AttributeService import AttributeService
from app.annotations.services.ContactService import ContactService
from app.annotations.services.NoteService import NoteService
from app.annotations.v1.use_case.CreateAttribute import CreateAttribute
from app.annotations.v1.use_case.CreateContact import CreateContact
from app.annotations.v1.use_case.CreateNote import CreateNote
from app.annotations.v1.use_case.DeleteAttribute import DeleteAttribute
from app.annotations.v1.use_case.DeleteAttributeByContact import DeleteAttributeByContact
from app.annotations.v1.use_case.DeleteContact import DeleteContact
from app.annotations.v1.use_case.DeleteNote import DeleteNote
from app.annotations.v1.use_case.GetAttributes import GetAttributes
from app.annotations.v1.use_case.GetAttributesByContact import GetAttributesByContact
from app.annotations.v1.use_case.GetContacts import GetContacts
from app.annotations.v1.use_case.GetNoteByContact import GetNoteByContact
from app.annotations.v1.use_case.GetTagByContact import GetTagByContact
from app.annotations.v1.use_case.UpdateAttribute import UpdateAttribute
from app.annotations.repositories.TagRepository import TagRepository
from app.annotations.services.TagService import TagService
from app.annotations.v1.use_case.CreateTag import CreateTag
from app.annotations.v1.use_case.DeleteTag import DeleteTag
from app.annotations.v1.use_case.GetTags import GetTags
from app.annotations.v1.use_case.UpdateAttributeByContact import UpdateAttributeByContact
from app.annotations.v1.use_case.UpdateContacts import UpdateContact
from app.annotations.v1.use_case.UpdateNote import UpdateNote
from app.annotations.v1.use_case.UpdateTag import UpdateTag
from app.chat_bot.models.ChatBot import FlowNode
from app.chat_bot.repositories.ChatBotRepositories import ChatBotRepository
from app.chat_bot.services.ChatbotContextService import ChatbotContextService
from app.chat_bot.services.ChatBotService import ChatBotService
from app.chat_bot.v1.use_case.AddFlowNode import AddFlowNode
from app.chat_bot.v1.use_case.CreateChatBot import CreateChatBot
from app.chat_bot.v1.use_case.DeleteChatBot import DeleteChatBot
from app.chat_bot.v1.use_case.GetChatBots import GetChatBots
from app.chat_bot.v1.use_case.GetChatBotFlow import GetChatBotFlow
from app.chat_bot.v1.use_case.TriggerChatBot import TriggerChatBot
from app.core.exceptions.ErrorHandler import ErrorHandler
from app.core.logs.LogCRUD import LogCRUD
from app.core.logs.LoggingBaseMiddleWare import LoggingMiddleware
from app.core.logs.SystemLogService import SystemLogService
from app.core.services.HTTPClient import EnhancedHTTPClient
from app.events.pub.ChatBotTriggerPublisher import ChatBotTriggerPublisher
from app.events.pub.ChatbotFlowPublisher import ChatbotFlowPublisher
from app.chat_bot.v1.use_case.MakeChatBotDefault import MakeChatBotDefault
from app.events.pub.MessageBroadcastPublisher import MessageBroadcastPublisher
from app.core.broker.RabbitMQBroker import RabbitMQBroker,RabbitMQSettings
from app.events.pub.MessageReceivedPublisher import MessageHookReceivedPublisher
from app.events.pub.SystemLogsPublisher import SystemLogsPublisher
from app.events.pub.WhatsappMessagePublisher import  WhatsappMessagePublisher

from app.core.repository.MongoRepository import MongoCRUD
from app.core.services.S3Service import S3Service
from app.core.storage.redis import AsyncRedisService
from app.events.pub.test_everything import TestPublisher
from app.real_time.socketio.socket_gateway import SocketMessageGateway
from app.real_time.webhook.services.MessageHook import MessageHook
from app.real_time.webhook.services.TemplateHook import TemplateHook
from app.real_time.webhook.services.WebhookDispatcher import WebhookDispatcher
from app.user_management.user.repositories.UserRepository import UserRepository
from app.user_management.user.v1.use_case.DeleteTeam import DeleteTeam
from app.user_management.user.v1.use_case.EditTeam import EditTeam
from app.whatsapp.broadcast.repositories.BroadCastRepository import BroadcastRepository
from app.whatsapp.broadcast.services.BroadCastService import BroadcastService
from app.whatsapp.broadcast.use_case.BroadcastConfig import BroadcastConfig
from app.whatsapp.broadcast.use_case.BroadcastScheduler import BroadcastScheduler
from app.whatsapp.broadcast.use_case.CancelBroadcast import CancelBroadcast
from app.whatsapp.broadcast.use_case.GetBroadcasts import GetBroadcasts
from app.whatsapp.business_profile.external_services.BusinessProfileApi import BusinessProfileApi
from app.whatsapp.business_profile.v1.services.BusinessProfileService import BusinessProfileService
from app.whatsapp.business_profile.v1.use_case.UploadFileData import UploadFileData
from app.whatsapp.business_profile.v1.use_case.CreateUploadSession import CreateUploadSession
from app.whatsapp.business_profile.v1.use_case.GetBusinessProfile import GetBusinessProfile
from app.whatsapp.business_profile.v1.use_case.UpdateBusinessProfile import UpdateBusinessProfile
from app.whatsapp.business_profile.v1.use_case.UpdateProfilePicture import UpdateProfilePicture
from app.whatsapp.media.external_services.WhatsAppMediaApi import WhatsAppMediaApi
from app.whatsapp.media.v1.usecase.CreaeSession import CreateSession
from app.whatsapp.media.v1.usecase.DeleteMedia import DeleteMedia
from app.whatsapp.media.v1.usecase.DownloadMedia import DownloadMedia
from app.whatsapp.media.v1.usecase.RetrieveMediaUrl import RetrieveMediaUrl
from app.whatsapp.media.v1.usecase.UploadMedia import UploadMedia
from app.whatsapp.media.v1.usecase.UploadSession import UploadFileSession
from app.whatsapp.team_inbox.external_services.WhatsAppMessageApi import WhatsAppMessageApi
from app.whatsapp.team_inbox.models.Message import Message
from app.whatsapp.team_inbox.operations.SaveMessage import SaveMessage
from app.whatsapp.team_inbox.repositories.AssignmentRepository import AssignmentRepository
from app.whatsapp.team_inbox.repositories.ConversationRepository import ConversationRepository
from app.whatsapp.team_inbox.repositories.MessageRepository import MessageRepository
from app.whatsapp.team_inbox.services.AssignmentService import AssignmentService
from app.whatsapp.team_inbox.services.ConversationService import ConversationService
from app.whatsapp.team_inbox.services.MessageService import MessageService
from app.whatsapp.team_inbox.v1.use_case.AssignedUserToConversation import AssignedUserToConversation
from app.whatsapp.team_inbox.v1.use_case.GetConversationMessages import GetConversationMessages
from app.whatsapp.team_inbox.v1.use_case.GetUserConversations import GetUserConversations
from app.whatsapp.team_inbox.v1.use_case.CreateNewConversation import CreateNewConversation
from app.whatsapp.team_inbox.v1.use_case.LocationMessage import LocationMessage
from app.whatsapp.team_inbox.v1.use_case.MediaMessage import MediaMessage
from app.whatsapp.team_inbox.v1.use_case.ReplyWithReactionMessage import ReplyWithReactionMessage
from app.whatsapp.team_inbox.v1.use_case.TemplateMessage import TemplateMessage
from app.whatsapp.team_inbox.v1.use_case.TextMessage import TextMessage
from app.whatsapp.team_inbox.v1.use_case.UpdateConversationStatus import UpdateConversationStatus
from app.whatsapp.template.models.Template import Template
from app.whatsapp.template.repositories.TemplateRepositories import TemplateRepository
from app.whatsapp.template.services.TemplateService import TemplateService
from app.whatsapp.template.v1.usecase.CreateTemplate import CreateTemplate
from app.whatsapp.template.v1.usecase.DeleteTemplate import DeleteTemplate
from dependency_injector import containers, providers

from app.user_management.auth.repositories.RefreshTokenRepository import RefreshTokenRepository
from app.user_management.auth.repositories.RoleRepository import RoleRepository
from app.user_management.auth.services.RefreshTokenService import RefreshTokenService
from app.user_management.auth.services.RoleService import RoleService
from app.user_management.auth.v1.use_case.FrocePasswordResetByAdmin import ForcePasswordResetByAdmin
from app.user_management.auth.v1.use_case.ForceLogoutByAdmin import ForceLogoutByAdmin
from app.user_management.auth.v1.use_case.GetRoles import GetRoles
from app.user_management.auth.v1.use_case.TokenRefresh import TokenRefresh
from app.user_management.auth.v1.use_case.UserLogin import UserLogin
from app.user_management.auth.v1.use_case.UserLogout import UserLogout
from app.core.config.settings import Settings
from app.core.storage.postgres import PostgresDatabase, create_session
from app.user_management.user.repositories.ClientRepository import ClientRepository
from app.user_management.user.repositories.TeamRepository import TeamRepository
from app.user_management.user.services.ClientService import ClientService
from app.user_management.user.services.TeamService import TeamService
from app.user_management.user.services.UserService import UserService
from app.user_management.user.v1.use_case.CreateTeam import CreateTeam
from app.user_management.user.v1.use_case.CreateUser import CreateUser
from app.user_management.user.v1.use_case.DeleteUserById import DeleteUserById
from app.user_management.user.v1.use_case.EditUser import EditUser
from app.user_management.user.v1.use_case.GetTeams import GetTeams
from app.user_management.user.v1.use_case.GetUserInfo import GetUserInfo
from app.user_management.user.v1.use_case.GetUsersByClientId import GetUsersByClientId
from app.whatsapp. business_profile.v1.repository.BusinessProfileRepository import BusinessProfileRepository
from app.whatsapp.template.external_services.WhatsAppTemplateApi import WhatsAppTemplateApi
from app.whatsapp.template.v1.usecase.GetTemplates import GetTemplates
from botocore.config import Config as BotoConfig
from boto3.s3.transfer import TransferConfig
from socketio import AsyncServer,AsyncRedisManager
from app.core.logs.loggers import Logger
from app.core.storage.MongoDB import MongoDB
import boto3
import httpx
